from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(
        applicant_income,
        loan_amount,
        credit_score,
        prediction,
        probability,
        filename="Loan_Report.pdf"):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>CreditWise Loan Management System</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"Applicant Income : ₹ {applicant_income}", styles["BodyText"]))

    story.append(Paragraph(f"Loan Amount : ₹ {loan_amount}", styles["BodyText"]))

    story.append(Paragraph(f"Credit Score : {credit_score}", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    if prediction == 1:

        status = "APPROVED"

    else:

        status = "REJECTED"

    story.append(Paragraph(f"<b>Prediction :</b> {status}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Approval Probability :</b> {probability:.2f}%", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("Generated by CreditWise", styles["Italic"]))

    doc.build(story)